name:                evolution-simulator
version:             0.1.0.0
license:             AGPL-3

dependencies:
- GLFW
- GLFW
- GLUtil
- OpenGL
- ansi-terminal
- array
- base >= 4.7 && < 5
- containers
- fsnotify
- lens
- linear
- mtl
- stm
- storable-tuple
- time
- total-map

default-extensions:
- RankNTypes
- TemplateHaskell
- FlexibleContexts
- LambdaCase
- FlexibleInstances
- MultiParamTypeClasses
- GeneralizedNewtypeDeriving
- AllowAmbiguousTypes
- TypeApplications
- ScopedTypeVariables

library:
  source-dirs: src

executables:
  evolution-simulator-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - evolution-simulator