name:                evolution-simulator
version:             0.1.0.0
license:             AGPL-3

dependencies:
- array
- base >= 4.7 && < 5
- containers
- lens
- linear
- mtl
- random
- total-map

default-extensions:
- RankNTypes
- TemplateHaskell
- FlexibleContexts

library:
  source-dirs: src
